# Use an official OpenJDK runtime as the base image
FROM eclipse-temurin:23-jdk-alpine

# Set the working directory inside the container
WORKDIR /app


# Set environment variables
ENV NODE_ENV=Dev 

# Copy the built JAR file into the container
ARG JAR_FILE=target/spring-resource-server-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

# Expose the application's port (default for Spring Boot is 8080)
EXPOSE 8080

# Command to run the application when the container starts
ENTRYPOINT ["java", "-jar", "app.jar"]
